project_id = "hwdfhdegvfmhueheagyq"

[functions.helpscout]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.suggest-blog-topics]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
